server:
  port: 9999
spring:
  datasource:
    username: admin
    password: guanfei24
    url: jdbc:mysql://csci-test.cmso6a4fd2ju.us-east-2.rds.amazonaws.com:3306/mydb?characterEncoding=utf-8
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.management: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.management.*.entity
